name: Auto Assign to Project(s)

on:
  issues:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues and pull requests with `bug` or `enhancement` label to project
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.issue.labels.*.name, 'enhancement')
      with:
        project: 'https://github.com/Killaxy/dsa-ini-tracker/projects/1'
        column_name: 'TODO'